### ISSUE TITLE
Selenium message:no such element: Unable to locate element: {"method":"css selector","selector":".-next"}

### ISSUE THREAD

**Issue by speakame22** [Christianlee19/hockey-stats#1]
Christian - 

I ran across your article on how to scrape data from nhl.com/stats and got it working on my desktop for the URL you reference.  It worked great!  When I tried to change the URL to scrape different stats though, I keep getting this error when I run the loop function - 

Selenium message:no such element: Unable to locate element: {"method":"css selector","selector":".-next"}
  (Session info: chrome=95.0.4638.69)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T21:30:10'
System info: host: 'DESKTOP-PEANUT', ip: '192.168.86.88', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: unknown

Error: 	 Summary: NoSuchElement
 	 Detail: An element could not be located on the page using the given search parameters.
 	 class: org.openqa.selenium.NoSuchElementException
	 Further Details: run errorDetails method

The only things I have changed from your original code are the URL, the number of columns, and the number of pages in the loop function.  It doesn't make sense to me since nhl.com/stats generates the exact same type of page regardless of which stats you are selecting.  

For reference, here is the URL I'm trying to scrape - http://www.nhl.com/stats/skaters?report=scoringRates&reportType=season&seasonFrom=20092010&seasonTo=20182019&gameType=2&filter=gamesPlayed,gte,1&sort=goals5v5,goalsPer605v5&page=0&pageSize=50

Ideally I'd like to be able to scrape a few different URLs to look at stats in different ways.  Any idea what could be causing the error?  I appreciate any light you can shed on this.

**Comment by speakame22** [comment]
Christian - 
I figured it out.  Just had to adjust the sys.sleep because nhl.com was taking forever to load.  My problem seemed to be the code was running too fast and not giving the page enough time to load, so it couldn't find the "next" button.  You rock and thanks for posting this code.  It has helped tremendously!

**Comment by Christianlee19** [comment]
Hey, great to hear you figured it out and that the code was useful! The site is definitely slow sometimes so I tend to bump up the sys.sleep when looping through just to be safe - I should mention that in the article. Thanks for reading and it would be great to see your upcoming analyses
